language: python

env:
    - LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib LIBGIT2_VERSION=0.19.0

python:
  - "2.6"
  - "2.7"

before_install:
  - git clone --quiet --depth=1 git://github.com/libgit2/libgit2.git ~/libgit2
  - pushd ~/libgit2/ && git checkout v$LIBGIT2_VERSION && popd
  - mkdir -p ~/libgit2/build
  - pushd ~/libgit2/build && cmake .. -DCMAKE_INSTALL_PREFIX=~/libgit2/_install -DBUILD_CLAR=OFF && popd
  - pushd ~/libgit2/build && cmake --build . --target install && popd
  - ls -la ~/libgit2

install:
  - pip install -r requirements_test.txt --use-mirrors

script: nosetests

notifications:
  irc:
    - irc.freenode.org#blohg
