language: python

env:
    - LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib LIBGIT2_VERSION=0.20.0

python:
  - "2.7"

before_install:
  - git clone git://github.com/libgit2/libgit2.git ~/libgit2
  - pushd ~/libgit2/ > /dev/null && git checkout -qf v$LIBGIT2_VERSION && popd > /dev/null
  - mkdir -p ~/libgit2/build
  - pushd ~/libgit2/build > /dev/null && cmake .. -DCMAKE_INSTALL_PREFIX=~/libgit2/_install -DBUILD_CLAR=OFF && popd > /dev/null
  - pushd ~/libgit2/build > /dev/null && cmake --build . --target install && popd > /dev/null
  - ls -la ~/libgit2

install:
  - pip install -r requirements_test.txt --use-mirrors

script:
  - nosetests

notifications:
  irc:
    channels:
      - irc.freenode.org#blohg
    on_success: change
